# Generated by Django 5.0.6 on 2024-06-30 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(default='', max_length=300)),
                ('figura', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='', max_length=300)),
                ('correta', models.BooleanField(blank=True, default=False, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.pergunta')),
            ],
        ),
    ]
