# Generated by Django 5.0.6 on 2024-06-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_sobre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
