# Generated by Django 5.0.6 on 2024-06-19 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_imagem_post_post_resumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 19, 17, 55, 22, 491570, tzinfo=datetime.timezone.utc)),
        ),
    ]
