# Generated by Django 5.0.6 on 2024-06-30 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 30, 3, 39, 59, 207129, tzinfo=datetime.timezone.utc)),
        ),
    ]
