# Generated by Django 5.0.6 on 2024-06-30 21:43

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_conteudo_remove_post_resumo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
