# Generated by Django 5.0.6 on 2024-06-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tempo_leitura',
            field=models.CharField(default=30, max_length=2),
        ),
    ]
