# Generated by Django 5.0.6 on 2024-06-30 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_tempo_leitura_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 30, 22, 45, 57, 555163, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Assunto',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
