# Generated by Django 5.0.6 on 2024-07-02 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 2, 5, 46, 58, 904268, tzinfo=datetime.timezone.utc)),
        ),
    ]
