# Generated by Django 5.0.6 on 2024-07-03 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 3, 0, 10, 16, 865314, tzinfo=datetime.timezone.utc)),
        ),
    ]
