# Generated by Django 5.0.6 on 2024-07-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vestibular_livros'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='link_amazon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='link_pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='link_spotify',
            field=models.URLField(blank=True, null=True),
        ),
    ]
