# Generated by Django 5.0.6 on 2024-07-03 05:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_livro_link_amazon_livro_link_pdf_livro_link_spotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='resenha',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
