# Generated by Django 5.0.6 on 2024-07-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_livro_resenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.CharField(default=30, max_length=2),
        ),
    ]
