# Generated by Django 5.0.6 on 2024-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_livro_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='paginas',
            field=models.CharField(default=30, max_length=5),
        ),
    ]
